//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeupInventoryWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMovements
    {
        public int MovementID { get; set; }
        public string SKU { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string MovementType { get; set; }
        public Nullable<int> ProductStockBeforeMovement { get; set; }
        public Nullable<int> ProductStockAfterMovement { get; set; }
        public string Reason { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> MovementDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
